I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 865, in script
    all "За нас!"
TypeError: all() takes no keyword arguments

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 865, in script
    all "За нас!"
  File "C:\Users\nik21\OneDrive\Робочий стіл\навч\renpy-8.3.2-sdk\renpy\ast.py", line 2573, in execute
    Say.execute(self)
  File "C:\Users\nik21\OneDrive\Робочий стіл\навч\renpy-8.3.2-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\nik21\OneDrive\Робочий стіл\навч\renpy-8.3.2-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
TypeError: all() takes no keyword arguments

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
Novela 1.0
Tue Oct 29 16:03:07 2024
